spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
# The format used for the keystore. It could be set to JKS in case it is a JKS file
  ssl:
    key-store-type: PKCS12
  # The path to the keystore containing the certificate
    key-store: classpath:keystore/baeldung.p12
  # The password used to generate the certificate
    key-store-password: Grisha
  # The alias mapped to the certificate
